storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

tensorflow_version:
  value: "1.9.0"
  wizard:
    name: "Tensorflow version"
    kind: select
    options:
    - "1.2.0"
    - "1.3.0"
    - "1.4.0"
    - "1.5.0"
    - "1.6.0"
    - "1.7.0"
    - "1.8.0"
    - "1.9.0"
    - "1.10.0"
    - "1.10.1"

python_version:
  value: "3"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

jupyter:
  value: true
  wizard:
    name: Install Jupyter
    kind: boolean

tensorboard:
  value: true
  wizard:
    name: Install Tensorboard
    kind: boolean

serving_port:
 value: "9000"
 wizard:
   name: "Serving port"
   kind: "text"

src:
  value: https://github.com/kuberlab/tensorflow-examples
  accountId: ''
  revision: ''
  wizard:
    name: "Source Code"
    kind: git

dataset:
 value: ''
 version: ''
 workspace: ''
 wizard:
   name: "Dataset configuration"
   kind: dataset
